version: '3.5'

services:
    smonitor:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: supervisord-monitor
                CONTAINER_VERSION: 1.0.0
                DEBUG_TRACE: 0
                FROM_BASE: php5:20180402
            cache_from:
                - alpine:3.6
                - base_container:20180402
                - supervisord:20180402
                - php5:20180402
            context: .
            dockerfile: Dockerfile
        container_name: smonitor
        environment:
        environment:
            SMONITOR_PASS: ${CFG_PASS}
            SMONITOR_USER: ${CFG_USER}
        hostname: smonitor
        image: supervisord-monitor:20180402
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
