version: '3.3'

services:
    smonitor:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: smonitor
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}php/7.2.8-r1:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}nginx_base/1.15.3:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}php/7.2.8-r1:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: supervisord-monitor
        container_name: supervisorm
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SMONITOR_PASS_FILE: /run/secrets/smonitor.pwd
            SMONITOR_USER: $CFG_USER
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
#            PWD_PROTECTED: 'true'
#            WEB_USER_ID: $CFG_USER
#            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: smonitor
        image: ${DOCKER_REGISTRY:-}${OS:-}supervisord-monitor:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        secrets:
            - smonitor.pwd
            - supervisord.pwd
#            - web_user.pwd
        volumes:
            - ./vols/log:/var/log
            - ./build/container_build_framework/crf/bashlib:/usr/local/crf/bashlib

secrets:
   smonitor.pwd:
     file: ~/.inf/secrets/bobb.password
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
