version: '3.3'

services:
    smonitor:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: smonitor
                FROM_BASE: ${DOCKER_REGISTRY:-}php7:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}nginx_base:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}php8:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.branch: $CONTAINER_GIT_BRANCH
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: supervisord-monitor
                container.version: ${CONTAINER_VERSION:-3.0.0}
        container_name: smonitor
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SMONITOR_PASS: $CFG_PASS
            SMONITOR_USER: $CFG_USER
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
        hostname: smonitor
        image: ${DOCKER_REGISTRY:-}supervisord-monitor:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
            - ./build/container_build_framework/crf/bashlib:/usr/local/crf/bashlib
